name: share_plate1
description: A new Flutter project.

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Versioning information.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  permission_handler: ^8.3.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_dynamic_links: ^5.0.5
  flutter_native_splash: ^2.3.0
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.12
  flutter_stripe: ^9.5.0+1
  qr_code_dart_scan: ^0.7.5
  qr_bar_code_scanner_dialog: ^0.0.5
  adaptive_theme: ^3.6.0
  day_night_switcher: ^0.2.0+1
  getwidget: ^2.0.4
  flutter_credit_card: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true


flutter:
  uses-material-design: true
  assets:
    - assets/

  # Example for adding custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
